### ISSUE TITLE
Document radius server setup steps

### ISSUE THREAD

**Issue by anuragbhatia** [anuragbhatia/INNOG-IPv6-Mikrotik-workshop#1]
Please document steps needed to setup radius servers so that we can put appropriate playbook for it.

What we need is: 

1. Name of package(s) you install
2. File names you create or change to get the radius live

**Comment by rahulmkhj** [comment]
1.  Update default (netplan) yaml file with following:

- Add Interface to communicate with Private Network.
- Assign Documented IP(v6) to the New Interface.
- Add "routes" parameter with static route for Private Network, in out PoC setup it looked like the following:
```
network:
  ethernets:
    ens3:
      dhcp4: true
    ens7:
      dhcp4: false
      addresses:
        - 2001:db8::2/64
      routes:
        - to: 2001:db8::/32
          via: 2001:db8::1
  version: 2
```

2. Install "freeradius" Package.
```
$ sudo apt install freeradius
```
3. Add following snippet to the /etc/freeradius/3.0/clients.conf to allow 'Access-Request' packets from hosts in 2001:db8::/32 network.
```
client innog_lab {
   ipaddr = 2001:db8::/32
   secret=SomeRandomSharedSecret
}
```
4. Add user credentials that needs to authenticate against this radius server:
```
#reference format to add a user "test" with password "test"
test    Cleartext-Password:=test
        Acct-Interim-Interval:=5  #This is optional attributes to add to reply, one per line.
```
5. Finally restart the freeradius server for the changes to take effect:
```
$ sudo systemctl restart freeradius
```

Thats it!
