### ISSUE TITLE
Validate robot provisioning playbook 

### ISSUE THREAD

**Issue by anuragbhatia** [anuragbhatia/INNOG-IPv6-Mikrotik-workshop#10]
Goal should be: apt install ansible, git pull project and next ansible-playbook robot.yml and it should be ready to run things.

**Comment by anuragbhatia** [comment]
Missing setup of mgmt interface.

**Comment by anuragbhatia** [comment]
Netplan config to be added to playbooks: 

/etc/netplan/11-ens7.yaml

```
network:
  version: 2
  renderer: networkd
  ethernets:
    ens7:
      addresses:
         - 172.20.0.253/24
         - 2001:db8:d::253/64
```
